Repository EMPHATICSoft/emphaticsoft, pull requests merged in 2025-05, with the labels that each got.

#204 bump of classes_def version numbers
  RawData/classes_def.xml
  StandardRecord/classes_def.xml
Labels: bug

#216 Changed trackID in SRPID and arich in SRTrack, as agreed in WS
  CAFMaker/CAFMaker_module.cc
  StandardRecord/SRHeader.cxx
  StandardRecord/SRHeader.h
  StandardRecord/SRPID.cxx
  StandardRecord/SRPID.h
  StandardRecord/SRTrack.cxx
  StandardRecord/SRTrack.h
  StandardRecord/classes_def.xml
Labels: enhancement

#217 Bugfix/lackey32/module label data and sim
  ARICHReco/MakeArichCluster.fcl
  CAFMaker/CAFMaker.fcl
  CAFMaker/prod_reco_caf_job.fcl
  DataQuality/FillDataQuality.fcl
  Digitization/CMakeLists.txt
  Digitization/RelabelRawDigitModules.fcl
  Digitization/RelabelRawDigitModules_module.cc
  Digitization/digitization_job.fcl
  EventDisplay/EventDisplay3D_module.cc
  SSDReco/MakeSSDClusters.fcl
Labels: bug, enhancement
